### PR TITLE
rewrite using `secrets`

### LINKED ISSUE #1: Use 'secrets' module for cryptographically secure passwords
Nice project. But I would advise one change switch the use of the `random` module over to [`secrets`](https://docs.python.org/3/library/secrets.html#module-secrets). As pointed out in the documentation for the `random` module, this module is not made for cryptographic projects, the source of randomness is not good enough to prevent other people from recreating your passwords. It is better to make use of the pools of randomness provided by the operating system which can be accessed in the `secrets` module. I think the interface is sufficiently similar that a rewrite is very easy pull off.

If you want to discuss this in more detail, I would be happy to call.

### PR DESCRIPTION
**Pull request by joaomcteixeira**
Thanks a lot for your comments on #1 @douweschulte.

Could you comment on these changes? Are these appropriate?

I kept the `random.shuffle` at the end to compensate for the per-type char selection happening before; that is, guarantees the first chars are **not** mandatorily from different types.

### CODE REVIEW

**Comment by douweschulte** [comment]
Yes I think this is appropriate for now, in the best case the shuffle would also be based on the `secrets` module, which can possible be 'faked' easily by getting the seed for `random` from `secrets` and updating it just before every password generation. But that is not really necessary I think.

**Comment by joaomcteixeira** [comment]
Added also that.

Is a different implementation from that presented in the `secrets` official documentation, because they use a `while` loop to sample until a char is found and with several `for` to validate the pass has 3 chars of each type.

Here, I first choose one char of each type. Then, populate the rest, and final (after your suggestion) reshuffle using `secrets` 
again. The implementation here escalates, while the one in the docs doesn't. There's not much to escalate though, but I like to keep things this way.

I have to admit that visually, passwords look more random now with `secrets`.

Thanks a lot @douweschulte 
Let me know your final thoughts before merging.

**Comment by douweschulte** [comment]
Looks good to me!

**Comment by joaomcteixeira** [comment]
Thanks @douweschulte ! :relaxed:

**Pull request merged**
